[workspace]
resolver = "3"
members = ["asteroids", "asteroids_desktop", "asteroids_swift"]

[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace.dependencies]
asteroids = { path = "asteroids" }
bytemuck = { version = "1.25.2", features = ["derive"] }
pollster = "1.0.1"
wgpu = "30.0.1"
